'''Autor:Marta Lugo López
Fecha de entrega:'''

print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")


print("       *")
print("      * *")
print("     *   *")
print("    *     *")
print("   *       *")
print(" ****     ***")
print("    *     *")
print("    *     *")
print("    *     *")
print("    *     *")
print("    *     *")
print("    *     *")
print("    *     *")
print("    *     *")
print("    *     *")
print("    *******")


print("        *")
print("       * *")
print("      *   *")
print("     *     *")
print("    *       *")
print("   *         *")
print("  *           *")
print(" *             *")
print("******     ******")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *******")

